import { 
  MadrasaInfo, 
  MadrasaClass, 
  Student, 
  AttendanceRecord, 
  FeeReceipt, 
  TeacherStaff, 
  CashTransaction,
  HifzRecord,
  BoardingMealRecord,
  DailyBazarItem,
  StudentReportCard,
  DonationRecord
} from "@/types";

export const INITIAL_MADRASA: MadrasaInfo = {
  id: "mad_jamia_islamia",
  name: "জামিয়া ইসলামিয়া আরাবিয়া",
  muhtamimName: "মাওলানা মো. সাহাদাত হোসেন",
  type: "qawmi",
  activeDivisions: ["noorani", "hifz", "kitab"],
  slug: "jamia-islamia-arabia",
  address: "বড় মসজিদ রোড, জামিয়া কমপ্লেক্স, ঢাকা",
  phone: "01700000000",
  password: "123456",
  watermarkOpacity: 10,
  createdAt: "২০২৬-০১-০১",
};

export const INITIAL_CLASSES: MadrasaClass[] = [
  {
    "id": "cls_hifz",
    "name": "হিফজুল কুরআন",
    "division": "hifz",
    "sections": [
      "শাখা ক"
    ],
    "classTeacherName": "হাফেজ মাওলানা কারী জুবায়ের আহমেদ",
    "classTeacherPhone": "01711223344",
    "studentCount": 5
  },
  {
    "id": "cls_najera",
    "name": "নাজেরা বিভাগ",
    "division": "noorani",
    "sections": [
      "শাখা ক"
    ],
    "classTeacherName": "মাওলানা মোস্তাফিজুর রহমান",
    "classTeacherPhone": "01866778899",
    "studentCount": 5
  },
  {
    "id": "cls_shishu",
    "name": "শিশু শ্রেণি",
    "division": "noorani",
    "sections": [
      "শাখা ক"
    ],
    "classTeacherName": "কারী আব্দুর রহিম",
    "classTeacherPhone": "01977889900",
    "studentCount": 5
  },
  {
    "id": "cls_mizan",
    "name": "মিজান",
    "division": "kitab",
    "sections": [
      "শাখা ক"
    ],
    "classTeacherName": "মুফতি মিজানুর রহমান",
    "classTeacherPhone": "01755667788",
    "studentCount": 5
  }
];

export const INITIAL_STUDENTS: Student[] = [
  {
    "id": "STD-01",
    "roll": "০১",
    "name": "মোহাম্মদ আব্দুল্লাহ",
    "englishName": "Mohammad Abdullah",
    "classId": "cls_hifz",
    "className": "হিফজুল কুরআন",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৬:০০ - রাত ৯:০০",
    "formNumber": "১০১",
    "admissionDate": "২০২৫-০১-১০",
    "fatherName": "মাওলানা ফরিদ আহমেদ",
    "motherName": "আমেনা বেগম",
    "fatherOccupation": "শিক্ষক",
    "guardianName": "মাওলানা ফরিদ আহমেদ",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234501",
    "guardianPin": "1001",
    "emergencyPhone": "01811-234501",
    "emergencyContactName": "মাওলানা ফরিদ আহমেদ",
    "emergencyContactRelation": "পিতা",
    "birthCertificateNo": "20121915234001234",
    "guardianNid": "19821915234000567",
    "studentCategory": "মেধা বৃত্তিপ্রাপ্ত",
    "previousMadrasa": "দারুল উলুম মাদানিয়া",
    "previousTcInfo": "টিসি নং-৭৮৬",
    "address": "গ্রাম: রাজাপুর, ডাকঘর: সরাইল, জেলা: ব্রাহ্মণবাড়িয়া",
    "presentAddress": "গ্রাম: রাজাপুর, ডাকঘর: সরাইল, জেলা: ব্রাহ্মণবাড়িয়া",
    "permanentAddress": "গ্রাম: রাজাপুর, ডাকঘর: সরাইল, জেলা: ব্রাহ্মণবাড়িয়া",
    "birthDate": "২০১২-০৫-১৫",
    "bloodGroup": "B+",
    "monthlyFee": 1500,
    "khanaFee": 2500,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-01",
    "statusBadge": "সক্রিয়",
    "remarks": "মেধাবী ও সুশৃঙ্খল শিক্ষার্থী, নিয়মিত দরসে উপস্থিত থাকে।",
    "activities": [
      {
        "id": "act_1",
        "studentId": "STD-01",
        "date": "২০২৬-০৩-২০",
        "type": "praise",
        "title": "হিফজ প্রতিযোগিতা ১ম স্থান",
        "description": "বার্ষিক হুসনুত তিলাওয়াত প্রতিযোগিতায় হিফজ বিভাগে ১ম স্থান অধিকার করেছে।",
        "recordedBy": "মুহতামিম সাহেব"
      }
    ]
  },
  {
    "id": "STD-02",
    "roll": "০২",
    "name": "উমর ফারুক",
    "englishName": "Umar Faruk",
    "classId": "cls_hifz",
    "className": "হিফজুল কুরআন",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "হাফ ফ্রি",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৬:০০ - রাত ৯:০০",
    "formNumber": "১০২",
    "admissionDate": "২০২৫-০১-১২",
    "fatherName": "হাজী দেলোয়ার হোসেন",
    "motherName": "ফাতেমা খাতুন",
    "fatherOccupation": "ব্যবসায়ী",
    "guardianName": "হাজী দেলোয়ার হোসেন",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234502",
    "guardianPin": "1002",
    "emergencyPhone": "01811-234502",
    "emergencyContactName": "হাজী দেলোয়ার হোসেন",
    "emergencyContactRelation": "পিতা",
    "birthCertificateNo": "20131915234005678",
    "guardianNid": "19781915234000890",
    "studentCategory": "সাধারণ শিক্ষার্থী",
    "previousMadrasa": "মডেল নুরানী মাদরাসা",
    "previousTcInfo": "টিসি নং-২৩৪",
    "address": "উপশহর, সিলেট সদর, সিলেট",
    "presentAddress": "উপশহর, সিলেট সদর, সিলেট",
    "permanentAddress": "উপশহর, সিলেট সদর, সিলেট",
    "birthDate": "২০১৩-০৮-২০",
    "bloodGroup": "A+",
    "monthlyFee": 1500,
    "khanaFee": 1250,
    "dueAmount": 500,
    "isLillahScholarship": false,
    "barcode": "STD-02",
    "statusBadge": "সক্রিয়",
    "remarks": "হুসনে সওত ও সুন্দর তিলাওয়াত।",
    "activities": []
  },
  {
    "id": "STD-03",
    "roll": "০৩",
    "name": "উসমান গণি",
    "englishName": "Usman Gani",
    "classId": "cls_hifz",
    "className": "হিফজুল কুরআন",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "ফুল ফ্রি",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "হ্যাঁ",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৬:০০ - রাত ৯:০০",
    "formNumber": "১০৩",
    "admissionDate": "২০২৫-০১-১৫",
    "fatherName": "মরহুম আব্দুল কুদ্দুস",
    "motherName": "রাবেয়া বসরী",
    "fatherOccupation": "মরহুম",
    "guardianName": "রাবেয়া বসরী",
    "guardianRelation": "মাতা",
    "guardianPhone": "01711-234503",
    "guardianPin": "1003",
    "emergencyPhone": "01811-234503",
    "emergencyContactName": "রাবেয়া বসরী",
    "emergencyContactRelation": "মাতা",
    "birthCertificateNo": "20131915234009999",
    "guardianNid": "19851915234000333",
    "studentCategory": "এতিম শিক্ষার্থী (লিল্লাহ ফান্ড)",
    "previousMadrasa": "নড়িয়া কওমিয়া মাদরাসা",
    "previousTcInfo": "টিসি নং-৮৮",
    "address": "নড়িয়া, শরীয়তপুর",
    "presentAddress": "নড়িয়া, শরীয়তপুর",
    "permanentAddress": "নড়িয়া, শরীয়তপুর",
    "birthDate": "২০১৩-০৩-১০",
    "bloodGroup": "B+",
    "monthlyFee": 0,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": true,
    "barcode": "STD-03",
    "statusBadge": "সক্রিয়",
    "remarks": "লিল্লাহ বোর্ডিং এতিম ফান্ডভুক্ত।",
    "activities": []
  },
  {
    "id": "STD-04",
    "roll": "০৪",
    "name": "আলী হাসান",
    "englishName": "Ali Hasan",
    "classId": "cls_hifz",
    "className": "হিফজুল কুরআন",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "ডে শিফট",
    "classTime": "সকাল ৮:০০ - বিকাল ৫:০০",
    "formNumber": "১০৪",
    "admissionDate": "২০২৬-০১-০৫",
    "fatherName": "ডা. শফিকুল ইসলাম",
    "motherName": "তাহমিনা বেগম",
    "fatherOccupation": "চিকিৎসক",
    "guardianName": "ডা. শফিকুল ইসলাম",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234504",
    "guardianPin": "1004",
    "emergencyPhone": "01811-234504",
    "emergencyContactName": "তাহমিনা বেগম",
    "emergencyContactRelation": "মাতা",
    "birthCertificateNo": "20121915234007777",
    "guardianNid": "19801915234000111",
    "studentCategory": "সাধারণ শিক্ষার্থী",
    "previousMadrasa": "মিরপুর আইডিয়াল স্কুল",
    "previousTcInfo": "টিসি নং-৫০৫",
    "address": "মিরপুর-১০, ঢাকা",
    "presentAddress": "মিরপুর-১০, ঢাকা",
    "permanentAddress": "মিরপুর-১০, ঢাকা",
    "birthDate": "২০১২-১১-১২",
    "bloodGroup": "AB+",
    "monthlyFee": 1800,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-04",
    "statusBadge": "সক্রিয়",
    "remarks": "নিয়মিত শিক্ষার্থী।",
    "activities": []
  },
  {
    "id": "STD-05",
    "roll": "০৫",
    "name": "মুআয বিন জাবাল",
    "englishName": "Muadh Bin Jabal",
    "classId": "cls_hifz",
    "className": "হিফজুল কুরআন",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "হাফ ফ্রি",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "ডে শিফট",
    "classTime": "সকাল ৮:০০ - বিকাল ৫:০০",
    "formNumber": "১০৫",
    "admissionDate": "২০২৬-০১-০৭",
    "fatherName": "মো. রফিক উদ্দিন",
    "motherName": "কুলসুম আক্তার",
    "fatherOccupation": "কৃষিজীবী",
    "guardianName": "মো. রফিক উদ্দিন",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234505",
    "guardianPin": "1005",
    "emergencyPhone": "01811-234505",
    "address": "চৌদ্দগ্রাম, কুমিল্লা",
    "presentAddress": "চৌদ্দগ্রাম, কুমিল্লা",
    "permanentAddress": "চৌদ্দগ্রাম, কুমিল্লা",
    "birthDate": "২০১৩-০১-২৫",
    "bloodGroup": "O+",
    "monthlyFee": 800,
    "khanaFee": 0,
    "dueAmount": 400,
    "isLillahScholarship": false,
    "barcode": "STD-05",
    "statusBadge": "সক্রিয়",
    "remarks": "পরিশ্রমী ছাত্র।",
    "activities": []
  },
  {
    "id": "STD-06",
    "roll": "০৬",
    "name": "মোহাম্মদ বিন নূর",
    "englishName": "Mohammad Bin Noor",
    "classId": "cls_najera",
    "className": "নাজেরা বিভাগ",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৭:০০ - রাত ৮:০০",
    "formNumber": "১০৬",
    "admissionDate": "২০২৫-১২-১৩",
    "fatherName": "মাওলানা নুরুল ইসলাম",
    "motherName": "আমিনা খাতুন",
    "fatherOccupation": "ইমাম ও শিক্ষক",
    "guardianName": "মাওলানা নুরুল ইসলাম",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234506",
    "guardianPin": "1006",
    "emergencyPhone": "01811-234506",
    "address": "দাগনভূঞা, ফেনী",
    "presentAddress": "দাগনভূঞা, ফেনী",
    "permanentAddress": "দাগনভূঞা, ফেনী",
    "birthDate": "২০১৬-০৪-২০",
    "bloodGroup": "O+",
    "monthlyFee": 1200,
    "khanaFee": 2000,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-06",
    "statusBadge": "সক্রিয়",
    "remarks": "নাজেরা পারা সমাপ্তের পথে।",
    "activities": []
  },
  {
    "id": "STD-07",
    "roll": "০৭",
    "name": "তানভীর আহমেদ",
    "englishName": "Tanvir Ahmed",
    "classId": "cls_najera",
    "className": "নাজেরা বিভাগ",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "হাফ ফ্রি",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৭:০০ - রাত ৮:০০",
    "formNumber": "১০৭",
    "admissionDate": "২০২৬-০১-০৪",
    "fatherName": "মো. খোরশেদ আলম",
    "motherName": "নাজমা বেগম",
    "fatherOccupation": "ব্যবসায়ী",
    "guardianName": "মো. খোরশেদ আলম",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234507",
    "guardianPin": "1007",
    "emergencyPhone": "01811-234507",
    "address": "টঙ্গী, গাজীপুর",
    "presentAddress": "টঙ্গী, গাজীপুর",
    "permanentAddress": "টঙ্গী, গাজীপুর",
    "birthDate": "২০১৫-০৯-১৫",
    "bloodGroup": "A+",
    "monthlyFee": 600,
    "khanaFee": 1000,
    "dueAmount": 600,
    "isLillahScholarship": false,
    "barcode": "STD-07",
    "statusBadge": "সক্রিয়",
    "remarks": "তাজবীদ শিখছে।",
    "activities": []
  },
  {
    "id": "STD-08",
    "roll": "০৮",
    "name": "সালমান ফারসি",
    "englishName": "Salman Farsi",
    "classId": "cls_najera",
    "className": "নাজেরা বিভাগ",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "পুরাতন",
    "batchType": "মর্নিং",
    "classTime": "সকাল ৮:০০ - দুপুর ১২:৩০",
    "formNumber": "১০৮",
    "admissionDate": "২০২৫-১১-২০",
    "fatherName": "মোস্তাক আহমেদ",
    "motherName": "শাহিনা আক্তার",
    "fatherOccupation": "প্রবাসী",
    "guardianName": "শাহিনা আক্তার",
    "guardianRelation": "মাতা",
    "guardianPhone": "01711-234508",
    "guardianPin": "1008",
    "emergencyPhone": "01811-234508",
    "address": "পাঁচলাইশ, চট্টগ্রাম",
    "presentAddress": "পাঁচলাইশ, চট্টগ্রাম",
    "permanentAddress": "পাঁচলাইশ, চট্টগ্রাম",
    "birthDate": "২০১৬-০২-১০",
    "bloodGroup": "B+",
    "monthlyFee": 1000,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-08",
    "statusBadge": "সক্রিয়",
    "remarks": "নিয়মিত মক্তব ছাত্র।",
    "activities": []
  },
  {
    "id": "STD-09",
    "roll": "০৯",
    "name": "হামযা বিন আব্দুল মুত্তালিব",
    "englishName": "Hamza Bin Abdul Muttalib",
    "classId": "cls_najera",
    "className": "নাজেরা বিভাগ",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "হাফ ফ্রি",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "মর্নিং",
    "classTime": "সকাল ৮:০০ - দুপুর ১২:৩০",
    "formNumber": "১০৯",
    "admissionDate": "২০২৬-০১-০৮",
    "fatherName": "মো. জাকির হোসেন",
    "motherName": "রোকেয়া খাতুন",
    "fatherOccupation": "চালক",
    "guardianName": "মো. জাকির হোসেন",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234509",
    "guardianPin": "1009",
    "emergencyPhone": "01811-234509",
    "address": "জয়দেবপুর, গাজীপুর",
    "presentAddress": "জয়দেবপুর, গাজীপুর",
    "permanentAddress": "জয়দেবপুর, গাজীপুর",
    "birthDate": "২০১৫-১২-০৫",
    "bloodGroup": "AB+",
    "monthlyFee": 500,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-09",
    "statusBadge": "সক্রিয়",
    "remarks": "মাখরাজ সুন্দর।",
    "activities": []
  },
  {
    "id": "STD-10",
    "roll": "১০",
    "name": "খাব্বাব ইবনুল আরাত",
    "englishName": "Khabbab Ibnul Aratt",
    "classId": "cls_najera",
    "className": "নাজেরা বিভাগ",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "ফুল ফ্রি",
    "isBoardingMeal": "না",
    "isOrphan": "হ্যাঁ",
    "studentType": "নতুন",
    "batchType": "মর্নিং",
    "classTime": "সকাল ৮:০০ - দুপুর ১২:৩০",
    "formNumber": "১১০",
    "admissionDate": "২০২৬-০১-১০",
    "fatherName": "মরহুম হারুনুর রশিদ",
    "motherName": "সুফিয়া বেগম",
    "fatherOccupation": "মরহুম",
    "guardianName": "সুফিয়া বেগম",
    "guardianRelation": "মাতা",
    "guardianPhone": "01711-234510",
    "guardianPin": "1010",
    "emergencyPhone": "01811-234510",
    "address": "বাউফল, পটুয়াখালী",
    "presentAddress": "বাউফল, পটুয়াখালী",
    "permanentAddress": "বাউফল, পটুয়াখালী",
    "birthDate": "২০১৬-০৭-১৮",
    "bloodGroup": "O-",
    "monthlyFee": 0,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": true,
    "barcode": "STD-10",
    "statusBadge": "সক্রিয়",
    "remarks": "এতিম ছাত্র, ফ্রি বেতন।",
    "activities": []
  },
  {
    "id": "STD-11",
    "roll": "১১",
    "name": "তালহা বিন উবাইদুল্লাহ",
    "englishName": "Talha Bin Ubaidullah",
    "classId": "cls_shishu",
    "className": "শিশু শ্রেণি",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৮:০০ - বিকাল ৪:০০",
    "formNumber": "১১১",
    "admissionDate": "২০২৬-০১-০২",
    "fatherName": "মো. আব্দুর রহিম",
    "motherName": "সালমা আক্তার",
    "fatherOccupation": "ব্যবসায়ী",
    "guardianName": "মো. আব্দুর রহিম",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234511",
    "guardianPin": "1011",
    "emergencyPhone": "01811-234511",
    "address": "ভেড়ামারা, কুষ্টিয়া",
    "presentAddress": "ভেড়ামারা, কুষ্টিয়া",
    "permanentAddress": "ভেড়ামারা, কুষ্টিয়া",
    "birthDate": "২০১৮-০৩-১২",
    "bloodGroup": "A+",
    "monthlyFee": 1200,
    "khanaFee": 1800,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-11",
    "statusBadge": "সক্রিয়",
    "remarks": "নূরানী কায়দা সম্পন্ন।",
    "activities": []
  },
  {
    "id": "STD-12",
    "roll": "১২",
    "name": "যুবাইর বিন আওয়াম",
    "englishName": "Zubair Bin Awwam",
    "classId": "cls_shishu",
    "className": "শিশু শ্রেণি",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "মর্নিং",
    "classTime": "সকাল ৯:০০ - দুপুর ১২:৩০",
    "formNumber": "১১২",
    "admissionDate": "২০২৬-০১-০৩",
    "fatherName": "মো. মকবুল হোসেন",
    "motherName": "ফিরোজা বেগম",
    "fatherOccupation": "কৃষি",
    "guardianName": "মো. মকবুল হোসেন",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234512",
    "guardianPin": "1012",
    "emergencyPhone": "01811-234512",
    "address": "ঈশ্বরদী, পাবনা",
    "presentAddress": "ঈশ্বরদী, পাবনা",
    "permanentAddress": "ঈশ্বরদী, পাবনা",
    "birthDate": "২০১৮-০৬-২৫",
    "bloodGroup": "B+",
    "monthlyFee": 800,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-12",
    "statusBadge": "সক্রিয়",
    "remarks": "হাতের লেখা সুন্দর।",
    "activities": []
  },
  {
    "id": "STD-13",
    "roll": "১৩",
    "name": "সা'দ বিন আবি ওয়াক্কাস",
    "englishName": "Saad Bin Abi Waqqas",
    "classId": "cls_shishu",
    "className": "শিশু শ্রেণি",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "মর্নিং",
    "classTime": "সকাল ৯:০০ - দুপুর ১২:৩০",
    "formNumber": "১১৩",
    "admissionDate": "২০২৬-০১-০৬",
    "fatherName": "আলহাজ্ব কবির আহমেদ",
    "motherName": "খালেদা আক্তার",
    "fatherOccupation": "ব্যবসায়ী",
    "guardianName": "আলহাজ্ব কবির আহমেদ",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234513",
    "guardianPin": "1013",
    "emergencyPhone": "01811-234513",
    "address": "সিদ্ধিরগঞ্জ, নারায়ণগঞ্জ",
    "presentAddress": "সিদ্ধিরগঞ্জ, নারায়ণগঞ্জ",
    "permanentAddress": "সিদ্ধিরগঞ্জ, নারায়ণগঞ্জ",
    "birthDate": "২০১৮-০৮-১৪",
    "bloodGroup": "O+",
    "monthlyFee": 1000,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-13",
    "statusBadge": "সক্রিয়",
    "remarks": "নূরানী কায়দা ৩য় ভাগ।",
    "activities": []
  },
  {
    "id": "STD-14",
    "roll": "১৪",
    "name": "সাঈদ বিন যায়েদ",
    "englishName": "Said Bin Zayd",
    "classId": "cls_shishu",
    "className": "শিশু শ্রেণি",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "হাফ ফ্রি",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "মর্নিং",
    "classTime": "সকাল ৯:০০ - দুপুর ১২:৩০",
    "formNumber": "১১৪",
    "admissionDate": "২০২৬-০১-০৯",
    "fatherName": "মো. আতিকুর রহমান",
    "motherName": "হাসিনা বানু",
    "fatherOccupation": "দোকানি",
    "guardianName": "মো. আতিকুর রহমান",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234514",
    "guardianPin": "1014",
    "emergencyPhone": "01811-234514",
    "address": "সোনাপুর, নোয়াখালী",
    "presentAddress": "সোনাপুর, নোয়াখালী",
    "permanentAddress": "সোনাপুর, নোয়াখালী",
    "birthDate": "২০১৮-১০-০২",
    "bloodGroup": "AB+",
    "monthlyFee": 500,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-14",
    "statusBadge": "সক্রিয়",
    "remarks": "পড়াশোনায় মনোযোগী।",
    "activities": []
  },
  {
    "id": "STD-15",
    "roll": "১৫",
    "name": "আবু উবাইদাহ ইবনুল জাররাহ",
    "englishName": "Abu Ubaidah Ibnul Jarrah",
    "classId": "cls_shishu",
    "className": "শিশু শ্রেণি",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "ফুল ফ্রি",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "মর্নিং",
    "classTime": "সকাল ৯:০০ - দুপুর ১২:৩০",
    "formNumber": "১১৫",
    "admissionDate": "২০২৬-০১-১১",
    "fatherName": "সিরাজুল ইসলাম",
    "motherName": "মরিয়ম বেগম",
    "fatherOccupation": "দিনমজুর",
    "guardianName": "সিরাজুল ইসলাম",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234515",
    "guardianPin": "1015",
    "emergencyPhone": "01811-234515",
    "address": "মুক্তাগাছা, ময়মনসিংহ",
    "presentAddress": "মুক্তাগাছা, ময়মনসিংহ",
    "permanentAddress": "মুক্তাগাছা, ময়মনসিংহ",
    "birthDate": "২০১৮-১১-২০",
    "bloodGroup": "A-",
    "monthlyFee": 0,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": true,
    "barcode": "STD-15",
    "statusBadge": "সক্রিয়",
    "remarks": "অসহায় পরিবারের সন্তান, ফুল ফ্রি।",
    "activities": []
  },
  {
    "id": "STD-16",
    "roll": "১৬",
    "name": "মাহমুদ হাসান দেওবন্দী",
    "englishName": "Mahmud Hasan Deobandi",
    "classId": "cls_mizan",
    "className": "মিজান",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৭:০০ - রাত ১০:০০",
    "formNumber": "১১৬",
    "admissionDate": "২০২৫-০১-১০",
    "fatherName": "মাওলানা ইদ্রিস আলী",
    "motherName": "মুহতারামা রহিমা খাতুন",
    "fatherOccupation": "মুহাদ্দিস",
    "guardianName": "মাওলানা ইদ্রিস আলী",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234516",
    "guardianPin": "1016",
    "emergencyPhone": "01811-234516",
    "address": "ভাঙ্গা, ফরিদপুর",
    "presentAddress": "ভাঙ্গা, ফরিদপুর",
    "permanentAddress": "ভাঙ্গা, ফরিদপুর",
    "birthDate": "২০১০-০৪-০৫",
    "bloodGroup": "O+",
    "monthlyFee": 2000,
    "khanaFee": 3000,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-16",
    "statusBadge": "সক্রিয়",
    "remarks": "মীযান ও মুনশাআব ভালো এবারত হল করতে পারে।",
    "activities": []
  },
  {
    "id": "STD-17",
    "roll": "১৭",
    "name": "আনোয়ার শাহ কাশ্মীরি",
    "englishName": "Anwar Shah Kashmiri",
    "classId": "cls_mizan",
    "className": "মিজান",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "নিজ খোরাকী",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৭:০০ - রাত ১০:০০",
    "formNumber": "১১৭",
    "admissionDate": "২০২৫-০১-১২",
    "fatherName": "মো. শওকত আলী",
    "motherName": "জাহানারা বেগম",
    "fatherOccupation": "শিক্ষক",
    "guardianName": "মো. শওকত আলী",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234517",
    "guardianPin": "1017",
    "emergencyPhone": "01811-234517",
    "address": "শেরপুর, বগুড়া",
    "presentAddress": "শেরপুর, বগুড়া",
    "permanentAddress": "শেরপুর, বগুড়া",
    "birthDate": "২০১০-০৭-২২",
    "bloodGroup": "B+",
    "monthlyFee": 2000,
    "khanaFee": 3000,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-17",
    "statusBadge": "সক্রিয়",
    "remarks": "সরফ ও নাহুর কায়েদা ভালো স্মরণ থাকে।",
    "activities": []
  },
  {
    "id": "STD-18",
    "roll": "১৮",
    "name": "আশরাফ আলী থানভী",
    "englishName": "Ashraf Ali Thanvi",
    "classId": "cls_mizan",
    "className": "মিজান",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "হাফ ফ্রি",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "না",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৭:০০ - রাত ১০:০০",
    "formNumber": "১১৮",
    "admissionDate": "২০২৫-০১-১৫",
    "fatherName": "মো. লোকমান হেকিম",
    "motherName": "শাহিদা পারভীন",
    "fatherOccupation": "ব্যবসায়ী",
    "guardianName": "মো. লোকমান হেকিম",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234518",
    "guardianPin": "1018",
    "emergencyPhone": "01811-234518",
    "address": "শিবচর, মাদারীপুর",
    "presentAddress": "শিবচর, মাদারীপুর",
    "permanentAddress": "শিবচর, মাদারীপুর",
    "birthDate": "২০১১-০২-১৮",
    "bloodGroup": "A+",
    "monthlyFee": 1000,
    "khanaFee": 1500,
    "dueAmount": 500,
    "isLillahScholarship": false,
    "barcode": "STD-18",
    "statusBadge": "সক্রিয়",
    "remarks": "মুতালাআয় মনোযোগী।",
    "activities": []
  },
  {
    "id": "STD-19",
    "roll": "১৯",
    "name": "হুসাইন আহমদ মাদানী",
    "englishName": "Hussain Ahmad Madani",
    "classId": "cls_mizan",
    "className": "মিজান",
    "section": "শাখা ক",
    "status": "residential",
    "residentialType": "আবাসিক",
    "khorakiType": "ফুল ফ্রি",
    "isBoardingMeal": "হ্যাঁ",
    "isOrphan": "হ্যাঁ",
    "studentType": "পুরাতন",
    "batchType": "ফুল টাইম",
    "classTime": "সকাল ৭:০০ - রাত ১০:০০",
    "formNumber": "১১৯",
    "admissionDate": "২০২৫-০১-১৮",
    "fatherName": "মরহুম মুফতি তফাজ্জল",
    "motherName": "আসমা খাতুন",
    "fatherOccupation": "মরহুম",
    "guardianName": "আসমা খাতুন",
    "guardianRelation": "মাতা",
    "guardianPhone": "01711-234519",
    "guardianPin": "1019",
    "emergencyPhone": "01811-234519",
    "address": "গোলাপগঞ্জ, সিলেট",
    "presentAddress": "গোলাপগঞ্জ, সিলেট",
    "permanentAddress": "গোলাপগঞ্জ, সিলেট",
    "birthDate": "২০১০-১১-০৯",
    "bloodGroup": "O+",
    "monthlyFee": 0,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": true,
    "barcode": "STD-19",
    "statusBadge": "সক্রিয়",
    "remarks": "লিল্লাহ বোর্ডিং এতিম ফান্ডভুক্ত।",
    "activities": []
  },
  {
    "id": "STD-20",
    "roll": "২০",
    "name": "কাসেম নানুতবী",
    "englishName": "Qasim Nanotvi",
    "classId": "cls_mizan",
    "className": "মিজান",
    "section": "শাখা ক",
    "status": "non_residential",
    "residentialType": "অনাবাসিক",
    "khorakiType": "হাফ ফ্রি",
    "isBoardingMeal": "না",
    "isOrphan": "না",
    "studentType": "নতুন",
    "batchType": "ডে শিফট",
    "classTime": "সকাল ৮:০০ - বিকাল ৫:০০",
    "formNumber": "১২০",
    "admissionDate": "২০২৬-০১-০৫",
    "fatherName": "মাওলানা জহিরুল ইসলাম",
    "motherName": "নাছিমা আক্তার",
    "fatherOccupation": "শিক্ষক",
    "guardianName": "মাওলানা জহিরুল ইসলাম",
    "guardianRelation": "পিতা",
    "guardianPhone": "01711-234520",
    "guardianPin": "1020",
    "emergencyPhone": "01811-234520",
    "address": "উত্তরা, ঢাকা",
    "presentAddress": "উত্তরা, ঢাকা",
    "permanentAddress": "উত্তরা, ঢাকা",
    "birthDate": "২০১১-০৬-৩০",
    "bloodGroup": "AB+",
    "monthlyFee": 1500,
    "khanaFee": 0,
    "dueAmount": 0,
    "isLillahScholarship": false,
    "barcode": "STD-20",
    "statusBadge": "সক্রিয়",
    "remarks": "নিয়মিত তাকরারে উপস্থিত থাকে।",
    "activities": []
  }
];

export const INITIAL_TEACHERS: TeacherStaff[] = [
  {
    "id": "tch_1",
    "name": "মাওলানা মো. সাহাদাত হোসেন",
    "designation": "মুহতামিম ও শায়খুল হাদিস",
    "phone": "01700000000",
    "classAssigned": "দাওরায়ে হাদিস (বুখারী শরীফ)",
    "nid": "19852691234567890",
    "qualification": "দাওরায়ে হাদিস ফারেগ, উচ্চতর হাদিস গবেষণা",
    "salary": 45000,
    "joiningDate": "০১/০১/২০১৮",
    "hasPreviousExperience": "হ্যাঁ",
    "previousInstitution": "দারুল উলুম মাদানিয়া মাদরাসা",
    "experienceYears": 7,
    "experienceMonths": 6,
    "experienceDuration": "৭ বছর ৬ মাস"
  },
  {
    "id": "tch_2",
    "name": "মুফতি রফিকুল ইসলাম",
    "designation": "নায়েবে মুহতামিম ও মুহাদ্দিস",
    "phone": "01711223344",
    "classAssigned": "মেশকাত জামাত",
    "nid": "19882691234567891",
    "qualification": "দাওরায়ে হাদিস, ইফতা (ইসলামিক আইন)",
    "salary": 38000,
    "joiningDate": "০১/০৩/২০১৯",
    "hasPreviousExperience": "হ্যাঁ",
    "previousInstitution": "মাদরাসাতুল হাদিস ঢাকা",
    "experienceYears": 5,
    "experienceMonths": 0,
    "experienceDuration": "৫ বছর"
  },
  {
    "id": "tch_3",
    "name": "মাওলানা আব্দুল কুদ্দুস",
    "designation": "নাজেমে তালিমাত (শিক্ষা সচিব)",
    "phone": "01822334455",
    "classAssigned": "জালালাইন জামাত",
    "nid": "19872691234567892",
    "qualification": "দাওরায়ে হাদিস, তাফসির ও আরবি ভাষা",
    "salary": 35000,
    "joiningDate": "০১/০৭/২০১৯",
    "hasPreviousExperience": "হ্যাঁ",
    "previousInstitution": "আল জামিয়াতুল আরাবিয়া",
    "experienceYears": 4,
    "experienceMonths": 2,
    "experienceDuration": "৪ বছর ২ মাস"
  },
  {
    "id": "tch_4",
    "name": "মুফতি মাহমুদুল হাসান",
    "designation": "উস্তাদুল ফিকহ ও কিতাব",
    "phone": "01933445566",
    "classAssigned": "শরহে বেকায়া জামাত",
    "nid": "19902691234567893",
    "qualification": "দাওরায়ে হাদিস ও ইফতা",
    "salary": 32000,
    "joiningDate": "০১/০১/২০২০",
    "hasPreviousExperience": "হ্যাঁ",
    "previousInstitution": "দারুল উলুম দেওবন্দ শাখা",
    "experienceYears": 3,
    "experienceMonths": 0,
    "experienceDuration": "৩ বছর"
  },
  {
    "id": "tch_5",
    "name": "মাওলানা জাকারিয়া নোমান",
    "designation": "উস্তাদুল আদব (আরবি সাহিত্য)",
    "phone": "01755667788",
    "classAssigned": "কাফিয়া জামাত",
    "nid": "19922691234567894",
    "qualification": "আদব ও উলুমুল কুরআন ডিপ্লোমা",
    "salary": 30000,
    "joiningDate": "০১/০৫/২০২১",
    "hasPreviousExperience": "না",
    "previousInstitution": "",
    "experienceYears": 0,
    "experienceMonths": 0,
    "experienceDuration": "নতুন শিক্ষক (পূর্ব অভিজ্ঞতা নেই)"
  },
  {
    "id": "tch_6",
    "name": "মাওলানা মোস্তাফিজুর রহমান",
    "designation": "নাহু ও সরফ শিক্ষক",
    "phone": "01866778899",
    "classAssigned": "হেদায়াতুন্নাহব ও শরহে জামী",
    "nid": "19932691234567895",
    "qualification": "দাওরায়ে হাদিস",
    "salary": 28000,
    "joiningDate": "০১/০৮/২০২১",
    "hasPreviousExperience": "হ্যাঁ",
    "previousInstitution": "মাদরাসা বায়তুশ শরফ",
    "experienceYears": 2,
    "experienceMonths": 6,
    "experienceDuration": "২ বছর ৬ মাস"
  },
  {
    "id": "tch_7",
    "name": "মুফতি মিজানুর রহমান",
    "designation": "ইবতেদায়ী কিতাব শিক্ষক",
    "phone": "01977889900",
    "classAssigned": "মীযান ও মুনশাআব",
    "nid": "19942691234567896",
    "qualification": "দাওরায়ে হাদিস",
    "salary": 26000,
    "joiningDate": "০১/০১/২০২২",
    "hasPreviousExperience": "না",
    "previousInstitution": "",
    "experienceYears": 0,
    "experienceMonths": 0,
    "experienceDuration": "নতুন শিক্ষক (পূর্ব অভিজ্ঞতা নেই)"
  },
  {
    "id": "stf_1",
    "name": "মো. সাইফুল ইসলাম",
    "designation": "প্রধান হিসাবরক্ষক ও অফিস সহকারী",
    "phone": "01788990011",
    "classAssigned": "কেন্দ্রীয় দফতর",
    "nid": "19892691234567897",
    "qualification": "এমবিএ (অ্যাকাউন্টিং) ও আলিম",
    "salary": 26000,
    "joiningDate": "০১/০২/২০২০"
  },
  {
    "id": "stf_2",
    "name": "মাওলানা হাফেজ জুবায়ের",
    "designation": "নাজেমে দারুল ইক্বামাহ (হোস্টেল তত্ত্বাবধায়ক)",
    "phone": "01899001122",
    "classAssigned": "ছাত্রাবাস",
    "nid": "19912691234567898",
    "qualification": "হাফেজে কুরআন ও ফারেগ",
    "salary": 24000,
    "joiningDate": "০১/০৬/২০২০"
  },
  {
    "id": "stf_3",
    "name": "কারী আব্দুর রহমান",
    "designation": "প্রধান বাবুর্চি (বোর্ডিং মেস)",
    "phone": "01911223344",
    "classAssigned": "বোর্ডিং রান্নাঘর",
    "nid": "19832691234567899",
    "qualification": "অভিজ্ঞ মেস বাবুর্চি",
    "salary": 20000,
    "joiningDate": "০১/০১/২০১৯"
  },
  {
    "id": "stf_4",
    "name": "মো. রফিকুল হক",
    "designation": "খাদেম ও সিকিউরিটি গার্ড",
    "phone": "01722334455",
    "classAssigned": "মাদরাসা গেইট ও ক্যাম্পাস",
    "nid": "19862691234567800",
    "qualification": "প্রশিক্ষণপ্রাপ্ত সিকিউরিটি",
    "salary": 16000,
    "joiningDate": "১৫/০১/২০২০"
  }
];

export const INITIAL_TRANSACTIONS: CashTransaction[] = [
  // --- আজকের দিন (২২ মার্চ ২০২৬) ---
  {
    id: "tx_today_inc_1",
    type: "income",
    category: "কিতাব বিভাগের বেতন",
    fundType: "general",
    amount: 125000,
    date: "2026-03-22",
    description: "মার্চ মাসের আবাসিক ও অনাবাসিক কিতাবি ছাত্রদের বেতন আদায়",
    receiptNumber: "REC-2026-089"
  },
  {
    id: "tx_today_exp_1",
    type: "expense",
    category: "মেস ও কাঁচাবাজার",
    fundType: "general",
    amount: 45000,
    date: "2026-03-22",
    description: "২০০ জন ছাত্রের মেস বোর্ডিংয়ের পাইকারি বাজার (চাল, ডাল, মাছ, মাংস ও মসলা)",
    receiptNumber: "VOUCH-305"
  },
  {
    id: "tx_today_exp_2",
    type: "expense",
    category: "চিকিৎসা ও পথ্য",
    fundType: "general",
    amount: 2500,
    date: "2026-03-22",
    description: "অসুস্থ তালেবে ইলমের জরুরি ওষুধ ও পথ্য খরচ",
    receiptNumber: "VOUCH-306"
  },

  // --- গত এক সপ্তাহ (১৬ - ২১ মার্চ ২০২৬) ---
  {
    id: "tx_week_inc_1",
    type: "income",
    category: "দান ও অনুদান",
    fundType: "lillah_zakat",
    amount: 150000,
    date: "2026-03-21",
    description: "কুয়েত প্রবাসী দানশীল ভাইয়ের পক্ষ থেকে গরীব এতিম কিতাবি ছাত্রদের লিল্লাহ বোর্ডিং ফান্ডে দান",
    receiptNumber: "DON-2026-042"
  },
  {
    id: "tx_week_exp_1",
    type: "expense",
    category: "কিতাবখানা ও লাইব্রেরি",
    fundType: "general",
    amount: 12000,
    date: "2026-03-21",
    description: "মাদরাসার কিতাবখানার নতুন দরসী কিতাব ক্রয় ও বাঁধাই খরচ",
    receiptNumber: "VOUCH-304"
  },
  {
    id: "tx_week_inc_2",
    type: "income",
    category: "যাকাত তহবিল",
    fundType: "lillah_zakat",
    amount: 100000,
    date: "2026-03-20",
    description: "ব্যবসায়ী সমিতির পক্ষ থেকে এতিম ছাত্রদের খাদ্য সহায়তায় যাকাত প্রদান",
    receiptNumber: "DON-2026-040"
  },
  {
    id: "tx_week_exp_2",
    type: "expense",
    category: "বিদ্যুৎ বিল",
    fundType: "general",
    amount: 12000,
    date: "2026-03-18",
    description: "মাদরাসা ও ছাত্রাবাসের চলতি মাসের বিদ্যুৎ বিল পরিশোধ (ডেসকো)",
    receiptNumber: "VOUCH-303"
  },
  {
    id: "tx_week_exp_2_gas",
    type: "expense",
    category: "গ্যাস বিল",
    fundType: "general",
    amount: 6500,
    date: "2026-03-18",
    description: "বোর্ডিং ও রান্নাঘরের জন্য এলপিজি গ্যাস সিলিন্ডার ও গ্যাস বিল পরিশোধ",
    receiptNumber: "VOUCH-304"
  },

  // --- চলতি মাসের শুরু (০১ - ১৫ মার্চ ২০২৬) ---
  {
    id: "tx_month_inc_1",
    type: "income",
    category: "মাসিক অনুদান",
    fundType: "general",
    amount: 80000,
    date: "2026-03-15",
    description: "মাদরাসার স্থায়ী শুভাকাঙ্ক্ষী পরিষদের মাসিক সাহায্য",
    receiptNumber: "DON-2026-038"
  },
  {
    id: "tx_month_exp_1",
    type: "expense",
    category: "মেস ও বোর্ডিং",
    fundType: "general",
    amount: 32000,
    date: "2026-03-10",
    description: "ছাত্রদের ডাইনিং হলের প্রথম দশকের মুদি সামগ্রী ও সয়াবিন তেল ক্রয়",
    receiptNumber: "VOUCH-302"
  },
  {
    id: "tx_month_inc_2",
    type: "income",
    category: "ভর্তি ও সেশন ফি",
    fundType: "general",
    amount: 100000,
    date: "2026-03-05",
    description: "কিতাবি বিভাগের নতুন ছাত্রদের সেশন ও সেমিস্টার ফি বাবদ আয়",
    receiptNumber: "REC-2026-070"
  },
  {
    id: "tx_month_exp_2",
    type: "expense",
    category: "শিক্ষক ও স্টাফ বেতন",
    fundType: "general",
    amount: 185000,
    date: "2026-03-01",
    description: "মাদরাসার সকল মুহাদ্দিস, উস্তাদ ও খাদেমগণের মাসিক সম্মানী ও হাদিয়া প্রদান",
    receiptNumber: "VOUCH-301"
  },

  // --- গত মাস (ফেব্রুয়ারি ২০২৬) ---
  {
    id: "tx_feb_inc_1",
    type: "income",
    category: "জেনারেল ফান্ড অনুদান",
    fundType: "general",
    amount: 100000,
    date: "2026-02-25",
    description: "ফেব্রুয়ারি মাসের সাধারণ দান ও মেহমানদের হাদিয়া",
    receiptNumber: "DON-2026-030"
  },
  {
    id: "tx_feb_exp_1",
    type: "expense",
    category: "মেস ও কাঁচাবাজার",
    fundType: "general",
    amount: 34000,
    date: "2026-02-22",
    description: "ফেব্রুয়ারি শেষ সপ্তাহের মাছ ও শাকসবজি বাজার",
    receiptNumber: "VOUCH-204"
  },
  {
    id: "tx_feb_exp_2",
    type: "expense",
    category: "বিদ্যুৎ বিল",
    fundType: "general",
    amount: 16500,
    date: "2026-02-18",
    description: "ফেব্রুয়ারি মাসের বিদ্যুৎ বিল পরিশোধ",
    receiptNumber: "VOUCH-203"
  },
  {
    id: "tx_feb_inc_2",
    type: "income",
    category: "দান ও অনুদান",
    fundType: "lillah_zakat",
    amount: 200000,
    date: "2026-02-15",
    description: "এতিম ফান্ডে দানশীল হাজী সাহেবের এককালীন অনুদান",
    receiptNumber: "DON-2026-025"
  },
  {
    id: "tx_feb_exp_3",
    type: "expense",
    category: "মেস ও চাল ডাল",
    fundType: "general",
    amount: 38000,
    date: "2026-02-10",
    description: "ফেব্রুয়ারি মাসের মেস বোর্ডিংয়ের ১৫ দিনের চাল ও ডাল ক্রয়",
    receiptNumber: "VOUCH-202"
  },
  {
    id: "tx_feb_inc_3",
    type: "income",
    category: "কিতাব বিভাগের বেতন",
    fundType: "general",
    amount: 110000,
    date: "2026-02-05",
    description: "ফেব্রুয়ারি মাসের ছাত্র মাসিক বেতন আদায়",
    receiptNumber: "REC-2026-055"
  },
  {
    id: "tx_feb_exp_4",
    type: "expense",
    category: "শিক্ষক ও স্টাফ বেতন",
    fundType: "general",
    amount: 175000,
    date: "2026-02-01",
    description: "ফেব্রুয়ারি মাসের শিক্ষক ও কর্মচারীদের বেতন ভাতা পরিশোধ",
    receiptNumber: "VOUCH-201"
  }
];

export const INITIAL_DONATIONS: DonationRecord[] = [
  {
    id: "don_1",
    donorName: "হাজী মুহাম্মদ আকরাম আলী",
    phone: "01711223399",
    type: "zakat",
    amount: 100000,
    date: "2026-03-20",
    receiptNumber: "DON-2026-040",
    purpose: "এতিম কিতাবি ছাত্রদের খাবার ও চিকিৎসা সহায়তা",
    address: "গুলশান-২, ঢাকা",
    paymentMethod: "bank"
  },
  {
    id: "don_2",
    donorName: "কুয়েত প্রবাসী আলহাজ্ব রফিকুল ইসলাম",
    phone: "01755667788",
    type: "zakat",
    amount: 150000,
    date: "2026-03-21",
    receiptNumber: "DON-2026-042",
    purpose: "গরীব এতিম কিতাবি ছাত্রদের লিল্লাহ বোর্ডিং ফান্ড",
    address: "কুয়েত / চাঁদপুর",
    paymentMethod: "bank"
  },
  {
    id: "don_3",
    donorName: "ব্যবসায়ী সমিতি, চকবাজার",
    phone: "01811445566",
    type: "zakat",
    amount: 100000,
    date: "2026-03-20",
    receiptNumber: "DON-2026-041",
    purpose: "এতিম ছাত্রদের রমজান খাদ্য সহায়তা",
    address: "চকবাজার, ঢাকা",
    paymentMethod: "cash"
  },
  {
    id: "don_4",
    donorName: "মাওলানা আব্দুস সাত্তার",
    phone: "01822334400",
    type: "sadqa",
    amount: 50000,
    date: "2026-03-21",
    receiptNumber: "DON-2026-002",
    purpose: "মাদরাসার কিতাবখানা ও লাইব্রেরির কিতাব ক্রয় বাবদ",
    address: "উত্তরা, ঢাকা",
    paymentMethod: "bkash"
  },
  {
    id: "don_5",
    donorName: "স্থায়ী শুভাকাঙ্ক্ষী পরিষদ",
    phone: "01999887766",
    type: "general",
    amount: 80000,
    date: "2026-03-15",
    receiptNumber: "DON-2026-038",
    purpose: "মাদরাসার স্থায়ী শুভাকাঙ্ক্ষী পরিষদের মাসিক অনুদান",
    address: "যাত্রাবাড়ী, ঢাকা",
    paymentMethod: "bank"
  },
  {
    id: "don_6",
    donorName: "মুহতারাম ড. মুস্তাক আহমেদ",
    phone: "01733445577",
    type: "fitra",
    amount: 30000,
    date: "2026-03-12",
    receiptNumber: "DON-2026-036",
    purpose: "অগ্রিম সাদাকাতুল ফিতর ও এতিম তহবিলে দান",
    address: "ধানমন্ডি, ঢাকা",
    paymentMethod: "bkash"
  },
  {
    id: "don_7",
    donorName: "চামড়া ব্যবসায়ী কাফেলা",
    phone: "01677889900",
    type: "general",
    amount: 20000,
    date: "2026-03-08",
    receiptNumber: "DON-2026-034",
    purpose: "মাদরাসার সাধারণ উন্নয়ন ফান্ড",
    address: "হেমায়েতপুর, সাভার",
    paymentMethod: "cash"
  },
  {
    id: "don_8",
    donorName: "হাজী বোরহান উদ্দিন (লন্ডন প্রবাসী)",
    phone: "01700112233",
    type: "zakat",
    amount: 200000,
    date: "2026-02-15",
    receiptNumber: "DON-2026-025",
    purpose: "এতিম ফান্ডে দানশীল হাজী সাহেবের এককালীন অনুদান",
    address: "লন্ডন / সিলেট",
    paymentMethod: "bank"
  },
  {
    id: "don_9",
    donorName: "আল-মদিনা এন্টারপ্রাইজ",
    phone: "01722998811",
    type: "general",
    amount: 50000,
    date: "2026-02-25",
    receiptNumber: "DON-2026-030",
    purpose: "ফেব্রুয়ারি মাসের সাধারণ দান ও মেহমানদের হাদিয়া",
    address: "মতিঝিল, ঢাকা",
    paymentMethod: "bank"
  }
];

export const INITIAL_HIFZ_RECORDS: HifzRecord[] = [
  {
    id: "hfz_1",
    studentId: "STD-01",
    studentName: "মোহাম্মদ আব্দুল্লাহ",
    roll: "০১",
    date: "২০২৬-০৩-২২",
    sabakPara: "পারা ৩০",
    sabakSurah: "সূরা আন-নাবা",
    sabakPage: "পুরো পৃষ্ঠা",
    sabkiPara: "পারা ২৯",
    amparaSurah: "আমপারা রিভিশন",
    quality: "mumtaz",
    teacherRemarks: "মাশাআল্লাহ, উচ্চারণ অত্যন্ত চমৎকার ও বিশুদ্ধ তাজবীদ।"
  },
  {
    id: "hfz_2",
    studentId: "STD-02",
    studentName: "উমর ফারুক",
    roll: "০২",
    date: "২০২৬-০৩-২২",
    sabakPara: "পারা ১৫",
    sabakSurah: "সূরা বনী ইসরাঈল",
    sabakPage: "আধা পৃষ্ঠা",
    sabkiPara: "পারা ১৪",
    amparaSurah: "আমপারা রিভিশন",
    quality: "mumtaz",
    teacherRemarks: "মাশাআল্লাহ, ভালো হিফজ মুখস্থ করেছে।"
  }
];

export const INITIAL_MEALS: BoardingMealRecord[] = [
  {
    id: "ml_1",
    date: "২০২৬-০৩-২২",
    studentId: "STD-01",
    studentName: "মোহাম্মদ আব্দুল্লাহ",
    roll: "০১",
    className: "হিফজুল কুরআন",
    breakfast: true,
    lunch: true,
    dinner: true,
    guestMeals: 0
  },
  {
    id: "ml_2",
    date: "২০২৬-০৩-২২",
    studentId: "STD-02",
    studentName: "উমর ফারুক",
    roll: "০২",
    className: "হিফজুল কুরআন",
    breakfast: true,
    lunch: true,
    dinner: true,
    guestMeals: 1
  },
  {
    id: "ml_3",
    date: "২০২৬-০৩-২২",
    studentId: "STD-06",
    studentName: "মোহাম্মদ বিন নূর",
    roll: "০৬",
    className: "নাজেরা বিভাগ",
    breakfast: true,
    lunch: true,
    dinner: true,
    guestMeals: 0
  },
  {
    id: "ml_4",
    date: "২০২৬-০৩-২২",
    studentId: "STD-16",
    studentName: "মাহমুদ হাসান দেওবন্দী",
    roll: "১৬",
    className: "মিজান",
    breakfast: true,
    lunch: true,
    dinner: true,
    guestMeals: 0
  }
];

export const INITIAL_BAZAR: DailyBazarItem[] = [
  {
    id: "bz_1",
    date: "2026-03-22",
    item: "মিনিকেট চাল (১০ বস্তা) ও মসুর ডাল",
    quantity: "৫০০ কেজি চাল, ৪০ কেজি ডাল",
    cost: 45000,
    shopperName: "কারী আব্দুর রহমান (প্রধান বাবুর্চি)"
  },
  {
    id: "bz_2",
    date: "2026-03-22",
    item: "চিকিৎসা পথ্য ও স্যালাইন",
    quantity: "জরুরি ওষুধপত্র",
    cost: 2500,
    shopperName: "মাওলানা হাফেজ জুবায়ের (হোস্টেল তত্ত্বাবধায়ক)"
  },
  {
    id: "bz_3",
    date: "2026-03-21",
    item: "কিতাবখানা দরসী কিতাব ক্রয় ও বাঁধাই",
    quantity: "১৫ সেট কিতাব",
    cost: 12000,
    shopperName: "মাওলানা মো. সাহাদাত হোসেন"
  },
  {
    id: "bz_4",
    date: "2026-03-18",
    item: "মাদরাসা ও ছাত্রাবাসের বিদ্যুৎ বিল",
    quantity: "মার্চ মাসের বিদ্যুৎ বিল",
    cost: 12000,
    shopperName: "খাদেম শফিকুল ইসলাম"
  },
  {
    id: "bz_4_gas",
    date: "2026-03-18",
    item: "রান্নাঘরের গ্যাস সিলিন্ডার ও গ্যাস বিল",
    quantity: "মার্চ মাসের গ্যাস",
    cost: 6500,
    shopperName: "খাদেম শফিকুল ইসলাম"
  },
  {
    id: "bz_5",
    date: "2026-02-22",
    item: "মাছ ও শাকসবজি পাইকারি বাজার",
    quantity: "৭০ কেজি রুই মাছ ও কাঁচাবাজার",
    cost: 34000,
    shopperName: "কারী আব্দুর রহমান (প্রধান বাবুর্চি)"
  },
  {
    id: "bz_6",
    date: "2026-02-18",
    item: "ফেব্রুয়ারি বিদ্যুৎ বিল",
    quantity: "ফেব্রুয়ারি মাসের বিদ্যুৎ",
    cost: 16500,
    shopperName: "খাদেম শফিকুল ইসলাম"
  },
  {
    id: "bz_7",
    date: "2026-02-10",
    item: "মেস বোর্ডিংয়ের ১৫ দিনের চাল ও সয়াবিন তেল",
    quantity: "৪০০ কেজি চাল, ১০০ লিটার তেল",
    cost: 38000,
    shopperName: "কারী আব্দুর রহমান (প্রধান বাবুর্চি)"
  }
];

export const INITIAL_REPORTS: StudentReportCard[] = [
  {
    "id": "rep_1",
    "studentId": "STD-16",
    "studentName": "মাহমুদ হাসান দেওবন্দী",
    "roll": "১৬",
    "className": "মিজান",
    "examName": "অর্ধবার্ষিক পরীক্ষা ২০২৬",
    "subjects": [
      {
        "subjectName": "মীযান ও মুনশাআব",
        "fullMarks": 100,
        "obtainedMarks": 96,
        "grade": "মুমতাজ (A+)"
      },
      {
        "subjectName": "ইলমুস সরফ",
        "fullMarks": 100,
        "obtainedMarks": 94,
        "grade": "মুমতাজ (A+)"
      },
      {
        "subjectName": "নাহবেমীর",
        "fullMarks": 100,
        "obtainedMarks": 92,
        "grade": "মুমতাজ (A+)"
      },
      {
        "subjectName": "উর্দুর ২য় কিতাব",
        "fullMarks": 100,
        "obtainedMarks": 95,
        "grade": "মুমতাজ (A+)"
      }
    ],
    "totalFullMarks": 400,
    "totalObtainedMarks": 377,
    "percentage": 94.25,
    "overallGrade": "মাক্ববুল মুমতাজ (A+)",
    "meritPosition": 1,
    "attendanceDays": 98,
    "characterRemark": "অত্যন্ত মেধাবী, বিনয়ী ও মুত্তাকী তালেবে ইলম।"
  }
];
